### ISSUE TITLE
React Native: Cannot set property 'onchangedevice' of undefined

### ISSUE THREAD

**Issue by dquessenberry** [sendbird/sendbird-calls-javascript#2]
I ran into an issue when attempting to initialize the SendBirdCall in a React Native application and I discovered that SendBirdCalls has a required dependency for  RN apps, so I thought I would at least document how I was able to resolve this issue. 

1) Install [react-native-webrtc](https://github.com/react-native-webrtc/react-native-webrtc). This RN module does not support autolinking, so manual setup is required. 
2) Add the following to your index.js
```javascript
import {AppRegistry} from 'react-native';
import App from './src/App';
import {name as appName} from './app.json';
import { registerGlobals } from 'react-native-webrtc'; // <-- ADD THIS LINE
registerGlobals();  // <-- ADD THIS LINE

AppRegistry.registerComponent(appName, () => App);
```

**Comment by jungdj** [comment]
Thanks for sharing your workaround.

However, while you can use most of WebRTC apis with react-native-webrtc, there are still some features missing such as `addTrack` in `RTCPeerConnection` and `getSenders` in `RTCPeerConnection`. react-native-webrtc supports only until M75, not has been updated for more than three months

react-native-webrtc can work pretty nice and I'm positive with using it,  but please keep in mind that **Sendbird is not officially supporting React Native yet**.
